### PR TITLE
Tweak our satchless fork for django 1.6

### PR DESCRIPTION
**Pull request by jdunck**

### CODE REVIEW

**Comment by dlinder** [comment]
Add defaults to BooleanFields

**Comment by dlinder** [comment]
There's an EmptyQuerySet in their example app, if you care.

**Comment by dlinder** [comment]
ok, think I'm done here for now.

**Comment by dlinder** [comment]
:fire: 
:tropical_drink: :moyai:

**Comment by dlinder** [comment]
@jgaren a quickie for ya since you reviewed the rest of 1.6

**Comment by jgaren** [comment]
&#10004;

**Pull request merged**
